# Generated by Django 5.1.5 on 2025-01-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledapicall',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
